print('Can not change it directly')
print()
stuff = ('hello', 'world', 'bye', 'now')
print(type(stuff))
print(stuff)
print()
stuff = list(stuff)
print(type(stuff))
print(stuff)
print()
stuff[2] = 'goodbye'
print(stuff)
print()
stuff = tuple(stuff)
print(type(stuff))
print(stuff)